[package]
name = "tui-kk"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

[package.metadata]
app_prefix = "tuikk"

[dependencies]
arc-swap = "1.9.2"
bollard = "0.21.1"
color-eyre = "0.6.5"
crossterm = "0.29.0"
directories = "6.0.0"
futures-util = "0.3.34"
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
smart-default = "0.7.1"
thiserror = "2.0.20"
tokio =  { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] } # full
toml = "1.1.6"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber =  { version = "0.3.23", features = ["env-filter"] }
tuikk_macros = { path = "./tuikk_macros" }

[build-dependencies]
toml = "1.1.6"
